-- AlterTable
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "cashlessPercent" DOUBLE PRECISION NOT NULL DEFAULT 10;
ALTER TABLE "QuoteTemplate" ADD COLUMN IF NOT EXISTS "cashlessPercent" DOUBLE PRECISION NOT NULL DEFAULT 10;
